public with sharing class GlobalConstants {
    public static final string DUPLICATE_CONTACT_EMAIL_TEMPLATE_NAME = 'Duplicate_Contact_List';
    public static final string CUSTOM_SETTINGS_DEFAULT_LEAD_OWNER = 'DefaultLeadOwnerId';
    public static final string CUSTOM_SETTINGS_DEFAULT_CONTACT_OWNER = 'DefaultContactOwnerId';
    public static final string CONVERTED_CONTACT_EMAIL_TEMPLATE_NAME = 'Converted_Contact_List';
}