public class XeroConfig {
	public static String CONSUMER_KEY = 'P4JKDGCM3GQGSBIYED3NFVFAZCVK5B';
	public static String CONSUMER_SECRET = '5H4VAPBOPDLZAZJDNYM4Q2DRBZOLJE';
	public static String API_BASE_URL = 'https://api.xero.com';
	public static String API_ENDPOINT_URL = 'https://api.xero.com/api.xro/2.0/';
	public static String FILES_ENDPOINT_URL = 'https://api.xero.com/files.xro/1.0/';
	public static String REQUEST_TOKEN_URL = 'https://api.xero.com/oauth/RequestToken';
	public static String AUTHENTICATE_URL = 'https://api.xero.com/oauth/Authorize';
	public static String ACCESS_TOKEN_URL = 'https://api.xero.com/oauth/AccessToken';
	public static String API_ENDPOINT_STEM = '/api.xro/2.0/';
	public static String FILES_ENDPOINT_STEM = '/files.xro/1.0/';
	public static String REQUEST_TOKEN_STEM = '/oauth/RequestToken';
	public static String AUTHENTICATE_STEM = '/oauth/Authorize';
	public static String ACCESS_TOKEN_STEM = '/oauth/AccessToken';
}